### ISSUE TITLE
Wrong variable type when default value is 'None'

### ISSUE THREAD

**Issue by Bcow7** [jbasko/configmanager#163]
When I set a default value as 'None' and the value in my JSON file is an integer I noticed that it returns a string.
### JSON file
```
{
	"test": 10
}
```
### Python
```
>>> config = PlainConfig(
...     schema={
...         'test': 10,
...     },
...     load_sources=['/config.json'],
...     auto_load=True
... )
>>> config.test
10
>>> config = PlainConfig(
...     schema={
...         'test': None,
...     },
...     load_sources=['/config.json'],
...     auto_load=True
... )
>>> config.test
'10'
>>> type(config.test)
<class 'future.types.newstr.newstr'>
```

**Comment by jbasko** [comment]
By default all values are strings. You have to either say that `test` is an integer explicitly, or the default has to be of that type.

P.S. How did you come across this library? I would not recommend using it now, I have not updated it, but I think this approach isn't great, this library tries to do too many things at the same time.

**Comment by Bcow7** [comment]
I found the library with Google. Is there another library that you would recommend to do similar things?
