### ISSUE TITLE
.yaml.load in PlainConfig instances does not work

### ISSUE THREAD

**Issue by haizaar** [jbasko/configmanager#165]
Found an issue it seems:

```bash
$ cat conf.yaml 
name: bar
$ python -c 'from configmanager import Config; c = Config(schema={"name": "foo"}); c.yaml.load("./conf.yaml"); print(c.name)'
<Item name 'bar'>
$ python -c 'from configmanager import PlainConfig; c = PlainConfig(schema={"name": "foo"}); c.yaml.load("./conf.yaml"); print(c.name)'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/.../lib/python3.6/site-packages/configmanager/persistence.py", line 47, in load
    self._rw.load_config_from_file(self._config, f, as_defaults=as_defaults)
  File "/home/.../lib/python3.6/site-packages/configmanager/persistence.py", line 191, in load_config_from_file
    config.load_values(self.yaml.load(file_obj, **kwargs), as_defaults=as_defaults)
  File "/home/.../lib/python3.6/site-packages/configmanager/sections.py", line 584, in load_values
    self[name].load_values(value, as_defaults=as_defaults)
AttributeError: 'str' object has no attribute 'load_values'
```

I.e. when trying to update exiting instance of `PlainConfig` through `.yaml.load` it breaks. Am I missing something?

```bash
$ python  --version
Python 3.6.2
$ pip freeze |grep -Ei '(yaml|config)'
configmanager==1.34.0
configparser==3.5.0
PyYAML==3.13
```

**Comment by jbasko** [comment]
Looks like a bug in PlainConfig I'm afraid.

**Comment by haizaar** [comment]
Do you think you'll have a capacity to fix it?

**Comment by jbasko** [comment]
Not before the weekend. If you're really enthusiastic I might look into it then. Although if you're after PlainConfig then configmanager is an overkill. Dataclasses make a much nicer and more flexible interface.

**Comment by haizaar** [comment]
It's not a biggie, but it would be nice to have it fixed eventually.

PlainConfig is appealing because it provides the same dot.dict interface that my home-grown tool uses - I'll replace its internals with your configmanager and I'm done.

If for Dataclasses you mean Python 3.7 [dataclasses](https://docs.python.org/3/library/dataclasses.html#module-dataclasses), then I'm not sure how does it fit my bill (we use [attrs](https://github.com/python-attrs/attrs) a lot, so I'm familiar with the concept) - I have bunch of yamls that I need to overlay and expose as a dictionary.

**Comment by haizaar** [comment]
Works great. Thanks for pushing the fix to PyPi!
