### ISSUE TITLE
Any reason for exact project dependencies in setup.py

### ISSUE THREAD

**Issue by haizaar** [jbasko/configmanager#168]
Good day again,

Looking at `setup.py,` it specifies exact versions in `install_requires`. Is there a particular reason for that?

From my experience, `setup.py` usually specifies broad version ranges of anticipated compatibility.

I'm asking particularly because using this project practically freezes version of the `six` package for any other software installed together with it.

Thank you.

**Comment by jbasko** [comment]
Hi, you're right. It's a bad idea, removed pinned versions of generally used libraries. Thanks for reporting. Fixed in v1.34.2

**Comment by haizaar** [comment]
Thanks for the quick fix!
